### ISSUE TITLE
aggregate returning 500

### ISSUE THREAD

**Issue by miguelpeixe** [InfoAmazonia/rede#41]
## Request

`http://localhost:3000/api/v1/measurements/aggregate?end=2015-08-11T12:07:22-03:00&parameter_id=atmospheric_pressure&resolution=day&sensor_id=55b67fa2d8a7cdb8733aa640&start=2015-07-12T12:07:22-03:00`
## Response

```
TypeError: Object 2015-07-12T12:07:22-03:00 has no method &#39;toDate&#39;<br> &nbsp; &nbsp;at exports.aggregate (/home/miguelpeixe/devel/ia-rede/app/controllers/measurements.js:132:21)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/miguelpeixe/devel/ia-rede/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/home/miguelpeixe/devel/ia-rede/node_modules/express/lib/router/route.js:110:13)<br> &nbsp; &nbsp;at Object.load (/home/miguelpeixe/devel/ia-rede/app/controllers/parameters.js:23:5)<br> &nbsp; &nbsp;at exports.loadByQueryStringIfDefined (/home/miguelpeixe/devel/ia-rede/app/controllers/parameters.js:31:42)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/miguelpeixe/devel/ia-rede/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/home/miguelpeixe/devel/ia-rede/node_modules/express/lib/router/route.js:110:13)<br> &nbsp; &nbsp;at Query.&lt;anonymous&gt; (/home/miguelpeixe/devel/ia-rede/app/controllers/sensors.js:22:7)<br> &nbsp; &nbsp;at /home/miguelpeixe/devel/ia-rede/node_modules/mongoose/node_modules/kareem/index.js:177:19<br> &nbsp; &nbsp;at /home/miguelpeixe/devel/ia-rede/node_modules/mongoose/node_modules/kareem/index.js:109:16<br> &nbsp; &nbsp;at process._tickCallback (node.js:448:13)
```

**Comment by miguelpeixe** [comment]
You forgot to set moment() to the req param.

Line `119` on `controllers/measurements.js`:

``` javascript
  var start = moment(req.query['start']);
```

Line `123` on `controllers/measurements.js`:

``` javascript
  var end = moment(req.query['end']);
```
